[#ftl/]
[#-- @ftlvariable name="regenerateKeyActionAvailable" type="boolean" --]
[#import "../../_utils/dialog.ftl" as dialog/]
[#import "../../_utils/message.ftl" as message/]
[#if regenerateKeyActionAvailable]
  [@dialog.confirm action="regenerate-key" key="warn"/]
[#else]
  [@dialog.view]
     [@message.print key="not-available"/]
  [/@dialog.view]
[/#if]
