[#ftl/]
[#setting number_format='0.######'/]

[#function class type]
  [#assign classList = ''/]
  [#if attributes['class']??]
    [#assign classList = attributes['class']/]
  [#else]
    [#assign classList = type/]
  [/#if]
  [#if fieldMessages?size > 0]
    [#assign classList = 'error ' + classList/]
  [/#if]
  [#return classList/]
[/#function]

[#function toString value]
  [#if value?is_number || value?is_boolean]
    [#return value?c]
  [#elseif value?is_markup_output]
    [#return value]
  [#else]
    [#return value?string]
  [/#if]
[/#function]

[#macro append_attributes excludes=["includeFormRow"]]
  [#compress]
    [#list attributes?keys as key]
      [#if !excludes?seq_contains(key)]
        [#if key == 'disabled' && attributes[key]]
          disabled="disabled"
        [#elseif key == 'multiple' && attributes[key]]
          multiple="multiple"
        [#elseif key != 'disabled' && key != 'multiple']
           ${key?string?replace("_", "-")}="${toString(attributes[key])}"
        [/#if]
      [/#if]
    [/#list]
  [/#compress]
[/#macro]

[#macro append_data_properties obj='']
  [#compress]
    [#if attributes['dataProperties']?? && obj != '']
      [#list attributes['dataProperties'] as property]
        [#assign value = ('((obj.' + property + ')!"")')?eval/]
        data-${property}="${toString(value)}"
      [/#list]
    [/#if]
  [/#compress]
[/#macro]

[#macro control_label includeFor=true]
[#if label?has_content || attributes['labelRaw']??]
<label [#if includeFor]for="${attributes['id']}"[/#if][#if fieldMessages?size > 0] class="error"[/#if]>${attributes['labelRaw']?has_content?then(attributes['labelRaw'], label?no_esc)}[#if required!false]<span class="required">*</span>[/#if][#t/]
[#if attributes['wideTooltip']??][#t/]
  <i class="fa fa-info-circle" data-additional-classes="wide" data-tooltip="${attributes['wideTooltip']}"></i>[#t/]
[/#if][#t/]
[#if attributes['tooltip']??][#t/]
  <i class="fa fa-info-circle" data-tooltip="${attributes['tooltip']}"></i>[#t/]
[/#if][#t/]
</label>[#t/]
[/#if]
[/#macro]

[#macro dynamic_attributes]
  [#list dynamicAttributes?keys as key]
<input type="hidden" name="${attributes['name']}@${key}" value="${dynamicAttributes[key]}"/>
  [/#list]
[/#macro]

[#macro errors]
  [#if fieldMessages?size > 0]
<span class="error">[#list fieldMessages as message]${message?string}[#if message_has_next], [/#if][/#list]</span>
  [/#if]
[/#macro]
